eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${random.uuid}
server:
  port: 9191
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/productservice
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
